### ISSUE TITLE
MemoryError with large STL files

### ISSUE THREAD

**Issue by gpfilip** [mancellin/capytaine#21]
Hello, 

Thank you for contributing capytaine, you've put together a very useful tool. 

I've had success in solving the radiation problem with the built-in geometries and relatively coarse STL geometries with approximately 20,000 triangles or fewer. When using larger STLs, I run into the following memory errors when solving the radiation problem:

MemoryError: Unable to allocate array with shape (53714, 53714) and data type complex128

In this example, the STL is composed of 59730 before using keep_immersed_part() to remove the parts above the free surface. This looks to be a ~2GB memory allocation which should not be a problem on my 126GB RAM workstation. Is it possible to work around this memory issue? 

Thank you

**Comment by mancellin** [comment]
Dear @gpfilip

Thank you for your interest.

Actually, each double precision complex number (`complex128`) is stored on 16 bytes, so the total might be closer to 40GB per matrix. The solver needs 2 of them.

It might be tight on your machine, because the code usually takes more RAM:
- It is allocating some matrices for intermediate computations (mostly in version 1.0, it should have improved in version 1.1).
- It keeps a cache of the last computed matrices to avoid some redundant computations. It can be changed by setting `matrix_cache_size` to 0 [in the parameters of the solver](https://ancell.in/capytaine/latest/user_manual/resolution.html).

Other ways to reduce the RAM usage:
- The computation can be run in single precision instead of double. But the code has to be recompiled manually, there is no convenient user interface for that at the moment.
- Use [the symmetries of your body](https://ancell.in/capytaine/latest/user_manual/cookbook.html#symmetric-body), if any.
- Use the experimental implementation of Hierarchical Matrices to compress the matrices. Unfortunately, it is still poorly documented and requires some manual tuning. Below is a minimal example if you want to test it on you problem. I'd recommend you make some validation tests on coarser meshes before you trust the results on finer meshes.

```python
import capytaine as cpt
import xarray as xr

buoy = cpt.Sphere(
    ntheta=80, nphi=80, clip_free_surface=True, clever=False,
)
buoy.add_translation_dof(name="Heave")

buoy = buoy.minced((16, 16, 1))  # Number of clusters in each direction. Should be powers of 2.

solver = cpt.BEMSolver(
    engine=cpt.HierarchicalToeplitzMatrixEngine(
        ACA_tol=1e-2,  # Relative tolerance when approximating matrices. The higher, the more approximate.
        ACA_distance=2.0,  # Minimum relative distance between clusters to use compression. The lower, the more approximate.
    ),
)

test_matrix = xr.Dataset(coords={'omega': [1.0], 'radiating_dof': ['Heave']})

ds = solver.fill_dataset(test_matrix, [buoy])
```

**Comment by gpfilip** [comment]
Thank you for a detailed response @mancellin, this information is very useful. I will investigate the experimental implementation and the other suggestions you listed.

**Comment by mancellin** [comment]
According to my latest tests, when setting `matrix_cache_size` to 0, the 53000 faces case should need approximately 80GB of RAM and thus pass on a 120GB RAM system. Can you confirm that @gpfilip ?

However, it will be very slow, because without a cache, the same (big) matrices are needlessly recomputed over and over.
I've made some optimizations: in the next version of Capytaine, the cache will be freed before a new computation and it should still fit in the RAM without recomputing the same matrices several times.
