### ISSUE TITLE
added mass matrix order of dofs mixed up

### ISSUE THREAD

**Issue by RubendeBruin** [mancellin/capytaine#23]
When calculating the added mass of a box (as test) the ORDER of the degrees of freedom in the added-mass matrix are not the same as in the problem definition:

```
import capytaine as cpt

bem_solver = cpt.BEMSolver()

boat = cpt.RectangularParallelepiped(size=(1, 1, 2), resolution=(10, 10, 20))
boat.add_all_rigid_body_dofs()
boat.keep_immersed_part()
boat.show()

# SOLVE BEM PROBLEMS
omega = 0.1
problems = []
problems += [cpt.RadiationProblem(omega=omega, body=boat, radiating_dof=dof) for dof in boat.dofs]
results = [bem_solver.solve(problem) for problem in problems]
dataset = cpt.assemble_dataset(results)

print('Order of DOFs (would expect surge, sway, .... yaw)')
print(dataset['radiating_dof'].values)

amass = dataset['added_mass'].values[0]

print('Diagonal terms of added-mass matrix')
for i in range(6):
    print(amass[i,i])
```

gives:

![afbeelding](https://user-images.githubusercontent.com/34062862/70924256-7eb8a700-2029-11ea-95ab-9dcb90e8fa37.png)

Order of DOFs (would expect surge, sway, .... yaw)
['Heave' 'Pitch' 'Roll' 'Surge' 'Sway' 'Yaw']

Diagonal terms of added-mass matrix
395.0093976031379
197.86496385733827
197.86494047731247
833.5463313197964
833.5463939012288
43.085692661295404

boat.dofs is still surge, sway,heave,roll,pitch,yaw. But in the assembled results the order has changed.

Also, what are the units of the added mass? I would expect something in the order of the displacement (1.0 m3) for surge and sway but I get 200?

**Comment by mancellin** [comment]
Dear Ruben,

About the order of the dofs, see issue #4.
I haven't took the time to improve this yet. Sorry for the inconvenience.

(Personally, it doesn't affect me that much, since I prefer to use `xarray` to call the dofs by their name and not by their indices, e.g.:
```
dataset['added_mass'].sel(influenced_dof="Heave", radiating_dof="Heave")
```
which is more explicit and less error-prone, especially when the dofs are not the six rigid ones and there is no obvious ordering.)


About the unit: it should be kilograms for the translation dofs (and the SI unit of the moments of inertia for the rotation dofs).
Here, surge and sway are 833 kg (the data are still coherent with the labels), which is of the same order of magnitude as the 1 m³ of water you are expecting.

**Comment by RubendeBruin** [comment]
Hi Mancellin,

thanks for your reply. Reading #4 I'm not not sure if it is wise to try to maintain the order. Possibly the best solution is to add a warning to the tutorial? I'm probably not the only xarray rooky who has problems with this.
On the other hand, you software is still much easier to use than wring a wamit input file. Even with these minor inconveniences. Great job!

**Comment by mancellin** [comment]
There is a [note in the documentation](https://ancell.in/capytaine/latest/user_manual/outputs.html), but maybe it would indeed be better to explain earlier in the tutorial that the dofs are meant to be accessed by their name and that their ordering may change.

Thank you for your feedback!

**Comment by mancellin** [comment]
FYI, in the newly released version, the dofs should stay in order in the dataset.
