### ISSUE TITLE
Artifacts in Heave Added Mass plot for thin Vertical Cylinders

### ISSUE THREAD

**Issue by sharmi0** [mancellin/capytaine#53]
Hi,
I need to use a thin vertical cylinder for part of my object and I'm getting weird behavior for heave added mass plotted against frequency. These effects seem to vanish as the ratio between length:radius increases. Do you have suggestions for why this may be happening and how to fix it? Thanks!

Length:Radius =0.5:2.5
![heavegraph_dampingplate](https://user-images.githubusercontent.com/80690027/114291886-dec23080-9a58-11eb-91b4-41f2942f7dd4.png)

Length:Radius =5:2.5
![heavegraph_dampingplateL5](https://user-images.githubusercontent.com/80690027/114291887-df5ac700-9a58-11eb-897e-06bbed41dc14.png)

Length:Radius =10:2.5
![heavegraph_dampingplateL10](https://user-images.githubusercontent.com/80690027/114291888-df5ac700-9a58-11eb-99ed-bc8394207c4c.png)

**Comment by mancellin** [comment]
The weird behavior for high frequencies might be due to [this bug](https://github.com/mancellin/capytaine/issues/38). Could you check if you have panels deeper than 8 wavelengths?

If not, I would need more details: could you share your code?

**Comment by sharmi0** [comment]
I don't believe so. The behaviors I showed were only for the 'damping_plate'. I was testing each of the objects that were added together in line 104 because the heave added mass of the entire object had weird behaviors. It looks like the 'damping_plate' is contributing a significant portion of those weird behaviors. If you'd like to see it, in line 104 you can comment out everything except 'damping_plate'.
[PEARL_capytainev1.zip](https://github.com/mancellin/capytaine/files/6296922/PEARL_capytainev1.zip)

Thank you!

**Comment by mancellin** [comment]
Thank you.
I managed to reproduce your results (cf. figure and code below). It does not seem to be a mesh convergence issue.

I was mostly worried about the constant plateau for high frequencies on the right of the graph, but it can actually makes sense: for low wavelength, the body is many wavelengths away from the free surface and the added mass converges to the added mass of a body without a free surface (dashed line). This appears later for the longer cylinder because it is closer from the free surface, I guess.

As for the hiccup just before, it might be a numerical artifact due to the transition to some asymptotic simplification somewhere in the code. I would have to check that out, but as long as it is not higher than a few percents, it is not really a priority.

![Figure_1](https://user-images.githubusercontent.com/31126826/114429469-b4d64e80-9bbd-11eb-96d3-cb993543d97b.png)

```python
import numpy as np
import xarray as xr
import capytaine as cpt
import matplotlib.pyplot as plt

def compute_and_plot(radius=1.0, length=0.3, resolution=4, color="C0"):
    # resolution in panels per meters
    body = cpt.VerticalCylinder(radius=radius, length=length, center=(0, 0, -5.0),
                                nr=int(radius*resolution), nx=int(length*resolution), ntheta=int(2*np.pi*radius*resolution))
    body.add_translation_dof(name="Heave")
    test_matrix = xr.Dataset(coords={'omega': np.linspace(1.0, 8.0, 20), 'radiating_dof': ["Heave"]})
    ds = cpt.BEMSolver().fill_dataset(test_matrix, [body])
    ds["added_mass"].plot(x="omega", marker='o', color=color, label="resolution = {} panels per meter".format(resolution))

    ref = cpt.BEMSolver().solve(cpt.RadiationProblem(body=body, free_surface=np.infty, omega=0.0, radiating_dof="Heave"))
    plt.hlines([ref.added_masses['Heave']], linestyle='--', color=color, xmin=1.0, xmax=8.0, label="no free surface")

compute_and_plot(resolution=5, color="C0")
compute_and_plot(resolution=10, color="C1")
compute_and_plot(resolution=15, color="C2")
plt.legend()
plt.show()
```

**Comment by sharmi0** [comment]
Thank you, this was super helpful!
