### ISSUE TITLE
automated hydrostatics computation

### ISSUE THREAD

**Issue by ryancoe** [mancellin/capytaine#64]
To get hydrostatics when using `capytaine` (and Nemoh), I mostly use [`Meshmagick`](https://github.com/LHEEA/meshmagick). This goes something like 

```python
from meshmagick import mesh as mm
from meshmagick import hydrostatics as hs

fb = cpt.FloatingBody.from_file(filename=fbname+'.stl', name=fbname)
hsa = hs.Hydrostatics(mm.Mesh(fb.mesh.vertices, fb.mesh.faces))
hsd = hsa.hs_data
m = hsd['disp_mass']

I = np.array([[hsd['Ixx'], -1*hsd['Ixy'], -1*hsd['Ixz']],
              [-1*hsd['Ixy'], hsd['Iyy'], -1*hsd['Iyz']],
              [-1*hsd['Ixz'], -1*hsd['Iyz'], hsd['Izz']]])
M = block_diag(m, m, m, I) # TODO - scale inertias if mass is specified by user

fb.mass = self.fb.add_dofs_labels_to_matrix(M)
kHS = block_diag(0,0,hsd['stiffness_matrix'],0)

fb.hydrostatic_stiffness = self.fb.add_dofs_labels_to_matrix(kHS)
```

@mancellin - what are your thoughts about incorporating this into `capytaine`?

**Comment by mancellin** [comment]
The issue is that it is easy for a single rigid body with 6 usual dofs, but the scope of Capytaine is much larger (including e.g. several rigid bodies, articulated bodies or flexible bodies). Rigid body dofs are not special in the code (they are just a field of vectors on the surface of the body) so automating the computation of the hydrostatics would be tricky.

Possible solutions for automation:
* Make the rigid body dofs special and somehow track them to be able to compute the hydrostatics at least for rigid bodies, even with non standard axis of rotation, and maybe articulated bodies.
* Implement a generic formula to compute hydrostatics for arbitrary motion/deformation. (I believe there are papers about that in the literature...) 

Both need a significant amount of work. In the mean time, I prefer to let the users do it manually. Maybe your code sample could be added to the docs?

Related: #55

**Comment by ryancoe** [comment]
Good points. I can definitely imagine handling multiple bodies without too much challenge, but generalized modes would take a bit more work. Maybe something to add to the cookbook (e.g., https://ancell.in/capytaine/latest/user_manual/cookbook.html#animation-of-the-rao)?

**Comment by ryancoe** [comment]
@cmichelenstrofer - has developed some _helper functions_ for finding the hydrostatics and inertial properties for rigid bodies. While this doesn't cover every case (e.g., deformation). Maybe he can post them here and @mancellin can say whether he would like them to be included in the [`tools`](https://github.com/mancellin/capytaine/tree/master/capytaine/tools) module?

**Comment by mancellin** [comment]
I'm in favor of keeping only an example in the documentation for now.

There is an undocumented function `body.mesh.to_meshmagick()` in Capytaine to convert a mesh. As for `mass_matrix_constant_density`, it might make more sense to add it to Meshmagick's hydrostatics module.

However, we need to check that the example added in #70 (but not published yet) is compatible with the new version of Meshmagick. Would you mind proposing an update or add a notice about the required version of Meshmagick ?
