### ISSUE TITLE
Normalisation of velocity potential / surface elevation

### ISSUE THREAD

**Issue by lottevandongen** [mancellin/capytaine#75]
Dear Capytaine users,

In some of the example work I saw a scaling parameter in front of the surface elevation or velocity potential, e.g. in animate_free_surface.py the surface elevation from the diffraction problem is scaled with 0.5. 
Is it correct that this is only to show a nice animation, and thus that the resulting wave field from the diffraction problem can be found by 

> incoming_waves_elevation + diffraction_elevation

Without a normalisation factor? 

Kind regards,
Lotte

**Comment by mancellin** [comment]
Τhe mathematical model is linear, so if you scale down the incoming waves amplitude, the amplitude of the diffracted waves and the body response are accordingly scaled down. For any scaling coefficient, the wave field is a valid mathematical solution. But since the model is meant physically to describe small waves and small motions, the animation looks weird for large amplitudes.

**Comment by lottevandongen** [comment]
Indeed, that's what I thought. Thanks for your quick response! The only important thing is thus to keep the ratio between diffracted and incident velocity potentials 1:1.

**Comment by lottevandongen** [comment]
I was thinking about this because when I am computing the amplitude of the surface elevations for the diffraction problem |se_i+se_d| over a symmetric grid around my object, I find that the average of this amplitude is smaller than 1. In other words, because the average over |se_i|=1 over the same grid is larger than |se_i+se_d|<1, I have the idea that something would go wrong in energy conservation. 

I computed this for a 200mx15mx0.5m barge (black dashed line), where I looked at the values for y=0, x in [-400,-20]U[20,400] (red line)
![figure](https://user-images.githubusercontent.com/63447681/120173841-bf4bb680-c204-11eb-9566-f605d8ec821e.png)

Do you believe this could indicate numerical errors? The grid cells for the surface elevation computation were taken smaller for the calculations, the figure just shows a rough sketch to show the situation.

My object is quite shallow, so maybe the small amplitude approximation could cause errors because of the small draft. Furthermore, do you have any idea whether having rectangular grid cells could cause errors when the aspect ratio gets too large?

**Comment by mancellin** [comment]
That is not so obvious to me that the average of |se_i| should be of the same as |se_i + se_d|. Are you sure of that?

> Furthermore, do you have any idea whether having rectangular grid cells could cause errors when the aspect ratio gets too large?

If you mean the mesh of the floating body, yes it could.
If you mean the mesh of the free surface for the free surface elevation, not it does not. The free surface elevation is basically computed independently at each cell centers and the shape or topology of the cells is unused.

**Comment by lottevandongen** [comment]
Indeed I meant the mesh of the floating body. Is there a general rule of thumb for avoiding a 'too rectangular mesh' or is the best way of finding out just trial and error? 
Thanks a lot for your help!

**Comment by mancellin** [comment]
I have no idea how much it could affect the results. If you do some tests, please share your insights :)

**Comment by oliviavitale35** [comment]
matthieu
i am working on a similar problem and encountering the same issue, where energy conservation seems to be violated. i attempted a limiting case with a rectangular body whose draft is nearly the length of the ocean depth (~40 m), width is 40m, and thickness is 10 m (attempting to avoid a long and thin body). i am looking at the reflection and transmission coeffs (how much of the wave energy is reflected back and how much of the wave energy makes it past the body) calculated as

K_r = (h_inc - h_dif)/h_inc
K_t = h_inc + h_dif/h_inc

where "inc" is the incident waves and "dif" is the diffracted waves (ignoring radiation)

these values should not sum to greater than 1, but they have been for my rectangular bodies (see fig). is there a way to resolve this in my mesh? or is there something else at hand?

thanks, olivia
<img width="766" alt="ktkr" src="https://github.com/capytaine/capytaine/assets/119702956/bfa35581-36a4-4a13-ade5-57a5adbaf089">

<img width="390" alt="mesh" src="https://github.com/capytaine/capytaine/assets/119702956/8dd937ff-29d8-4d09-8ac1-7db2e4ee7f02">

**Comment by mancellin** [comment]
@oliviavitale35 Could you clarify what you denote by h and how you computed it with Capytaine?
If this is meant to be the energy flux, shouldn't you average over a wavelength?

**Comment by oliviavitale35** [comment]
@mancellin i later realized i was making a mistake in my calculations, such that "h" is supposed to denote wave height in the equation, but i was using surface elevation (not quite the same, but still similar). i have since run analytical calculations using the potentials obtained from capytaine to get wave height and such.

my thinking for energy flux is that the height of the wave reflected back and the height of the wave transmitted past the body cannot sum to greater than the height of the incident wave, otherwise energy conservation would be violated. however, that is what i seem to be finding. i have properly calculated time averaged energy flux (although i do think i have a small error in my calculation)

<img width="608" alt="image" src="https://github.com/capytaine/capytaine/assets/119702956/d4a8736e-1134-4bb5-a4d0-150d1b7b414a">

however, i'm more concerned with extracting wave amplitude and then wave height. these are the amplitudes i calculate from the capytaine potential:

<img width="592" alt="image" src="https://github.com/capytaine/capytaine/assets/119702956/362aecef-d608-4de7-a4c5-7501318fd874">

the free surface elevation from those amplitudes:

<img width="574" alt="image" src="https://github.com/capytaine/capytaine/assets/119702956/c13e2b69-92f7-4baa-ac11-d29a05448d56">

and this is the wave elevation i obtained directly from capytaine for comparison to my calculations:

<img width="382" alt="image" src="https://github.com/capytaine/capytaine/assets/119702956/01a1d92f-a875-4a8e-98a9-51aae3626076">

at this point, i'm more so wondering if there's a way to calculate amplitude in capytaine. i'm working on comparing all my analytics to BEM.

**Comment by mancellin** [comment]
Sorry I haven't answered yet.

I'm very interested in clarifying and documenting the energy balance of linear potential flow simulations done with Capytaine. But I haven't had the time to really delve into the theory.


Trying to define the terms of your question about amplitudes:

The free surface elevation reads

$$ \eta(x, t) = \Re \left( \hat \eta (x) e^{-i \omega t} \right) $$ 

where $\hat \eta (x)$  is the complex-valued field returned by Capytaine. (I'm not sure which real-valued field you are plotting in your graphs. Is it $\eta(x, 0)$ ?)

For the incoming wave, $\hat \eta_\text{incoming} (x) = A e^{ikx}$ where $A$ is the wave amplitude. The wave height is $h = 2A$.

I guess you can define more generally the wave height at a position $x$ as

$$ h(x) = \max_t \eta(x, t) - \min_t \eta(x, t) = 2 |\hat \eta(x)|. $$

where you might want to take $\hat \eta = \hat \eta_\text{incoming} + \hat \eta_\text{diffraction}$.

Is it what you had in mind?

**Comment by oliviavitale35** [comment]
Yes, this is exactly what I had in mind. From the capytaine wave elevation output (denoted as Z here):
fse = solver.compute_free_surface_elevation(grid, diff_result)
incoming_fse = airy_waves_free_surface_elevation(grid, diff_result)
Z = np.real((incoming_fse + fse)) 

I obtain this:
<img width="509" alt="image" src="https://github.com/capytaine/capytaine/assets/119702956/bfd880b7-e22e-45f9-8fed-44580dfcb69b">

which does make sense, so i'm not sure where i'm going wrong in the derivation from potential to wave elevation. the corresponding amplitudes are derived from the complex wave elevation are:

<img width="439" alt="image" src="https://github.com/capytaine/capytaine/assets/119702956/a64734c1-8278-49ca-a622-5d519ca410fe">

[yes i am using  eta(x,0)]

in terms of energy balance theory, i've been working with the time-averaged energy flux via two methods. the first method requires the time and x-derivatives of potential time averaged, then integrated over depth:

<img width="231" alt="image" src="https://github.com/capytaine/capytaine/assets/119702956/bd09c59e-f975-40ec-bd91-8c429b0a056c">

where the bar indicates time-average. you can derive a relation to upstream and downstream amplitudes if you take x=0 (which is limiting) as:

<img width="625" alt="image" src="https://github.com/capytaine/capytaine/assets/119702956/8313527c-fbfa-4e1e-b479-d0d1800af726">

I want to reconcile the energy fluxes i obtain from the potential vs the energy flux i obtain from wave amplitudes (as well as where i'm pulling the wave amplitudes).

let me know what you think or if you see any immediate issues in my methods
